USE [master]
GO

/****** Object:  Database [Day3Task]    Script Date: 03-12-2025 15:07:12 ******/
CREATE DATABASE [Day3Task]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Day3Task', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Day3Task.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Day3Task_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Day3Task_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Day3Task].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Day3Task] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Day3Task] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Day3Task] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Day3Task] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Day3Task] SET ARITHABORT OFF 
GO

ALTER DATABASE [Day3Task] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Day3Task] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Day3Task] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Day3Task] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Day3Task] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Day3Task] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Day3Task] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Day3Task] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Day3Task] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Day3Task] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Day3Task] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Day3Task] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Day3Task] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Day3Task] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Day3Task] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Day3Task] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Day3Task] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Day3Task] SET RECOVERY FULL 
GO

ALTER DATABASE [Day3Task] SET  MULTI_USER 
GO

ALTER DATABASE [Day3Task] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Day3Task] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Day3Task] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Day3Task] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Day3Task] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Day3Task] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Day3Task] SET QUERY_STORE = ON
GO

ALTER DATABASE [Day3Task] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Day3Task] SET  READ_WRITE 
GO

